model: 'BSDSA'
network: 'ro_34'
task: 'snake'
resume: false
gpus: ([3])

train:
    optim: 'adam'
    lr: 1e-4
    milestones: (80, 120)
    gamma: 0.25
    batch_size: 1
    dataset: 'BSDSA_train'
    num_workers: 2
    epoch: 150
    scheduler: 'manual'
    gammas: [0.5, 0.1]
test:
    dataset: 'BSDSA_test'
    batch_size: 1

heads: {'ct_hm': 7, 'wh': 2}
segm_or_bbox: 'segm'
