model: 'kins'
network: 'ro_34'
task: 'snake'
resume: false
gpus: ([1])

train:
    optim: 'adam'
    lr: 1e-4
    milestones: (13, 20)
    gamma: 0.25
    batch_size: 12
    dataset: 'KinsTrain'
    num_workers: 4
    epoch: 25
    scheduler: 'manual'
    gammas: [0.5, 0.1]
test:
    dataset: 'KinsMini'
    batch_size: 1

heads: {'ct_hm': 7, 'wh': 2}
segm_or_bbox: 'segm'
